services:
  mysql:
    image: mysql:latest
    container_name: notice-mysql
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  redis:
    image: redis:6.2-alpine
    container_name: notice-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
volumes:
  mysql-data:
  redis-data: