spring:
  application:
    name: notice
  datasource:
    username: devuser
    password: secret
    url: jdbc:mysql://localhost:3307/devdb?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 5000
      max-lifetime: 595000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        format_sql: false
        generate_statistics: false
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  swagger-ui:
    path: /notice/swagger.html


